### ISSUE TITLE
erlang 18?

### ISSUE THREAD

**Issue by davper** [mdevilliers/rabbitmq-stamp#10]
Hi!

Any chance you could release a compiled package for erlang 18 and rabbitMq 3.6?

Thanks in advance!

**Comment by mdevilliers** [comment]
Could you try the plugin at the following path -

https://github.com/mdevilliers/rabbitmq-stamp/tree/new-structure-mk/compiled/1.0.4/rabbitmq_3_6_3/erlang_18

I would be really interested in any feedback of it running in a clustered rabbit setup?

If it is all good - i'll merge into master?

**Comment by mdevilliers** [comment]
Closing as no feedback
