### ISSUE TITLE
rabbitmq-stamp erlang19?

### ISSUE THREAD

**Issue by albertfle** [mdevilliers/rabbitmq-stamp#11]
Any release for compiled package for erlang19 and rabbitMq 3.6.3?

Best regards

**Comment by mdevilliers** [comment]
Could you try the plugin at the following path -

https://github.com/mdevilliers/rabbitmq-stamp/tree/new-structure-mk/compiled/1.0.4/rabbitmq_3_6_3/erlang_19

I would be really interested in any feedback of it running in a clustered rabbit setup?

If it is all good - i'll merge into master?

**Comment by mdevilliers** [comment]
@albertfle have you had a chance to try the plugin?

**Comment by mdevilliers** [comment]
Closing as no feedback
