### ISSUE TITLE
Version compiled for 3.6.10

### ISSUE THREAD

**Issue by sharryg** [mdevilliers/rabbitmq-stamp#13]
Hi,

We have tried using the version compiled for 3.6.3 with RabbitMQ 3.6.10, but we can't get the plugin to show up in the list to be enabled.  Is it possible to compile new versions for RabbitMQ 3.6.10 with Erlang 18/19?

Thanks,
Sam

**Comment by mdevilliers** [comment]
Hey Sam,

Were there any details in the log files as to why the plugin was not being loaded? 

The files on that branch were done for some other requests and they never got back to me with any feedback - I would treat them with suspicion ;-)

Compiling a version for yourself should be straightforward
 
- checkout the `new-structure-mk` branch
- change the line in the Makefile 

```
# sets the current version of rabbit rather than working of master
current_rmq_ref = rabbitmq_v3_6_10
```
- run `make`
- run `make tests`
- run `make dist`


Thanks,

Mark

**Comment by sharryg** [comment]
Hi Mark,

The issue we see is shown below:


[cid:92cf70a4-90a6-4606-9197-ad6fde4d30b9]

We've actually never set up a RabbitMQ dev environment before so are a bit unsure that we'll actually be doing it correctly.  We are also all windows developers so a bit unsure on setting up the linux VM using your vagrant script (the VMs we are using for the rabbit cluster are provided and supported by Bitnami and Microsoft on Azure, which is why we are restricted to 3.6.10 and Ubuntu LTS 14.04).

Would you mind just confirming that the error above is what you would expect when installing the 3.6.3 plugin into a 3.6.10 Rabbit instance?

Thanks,
Sam




________________________________

**Comment by mdevilliers** [comment]
Hey Sam,

I wouldn't expect any error I'm afraid and I don't recognize what you have there. Could you check the log files from this web page - https://www.rabbitmq.com/relocate.html ? Erlang is really good at reporting errors so I would expect to see something in there.
 
Of course the other thing to do is to run the plugin on your windows machine to recreate the bug. It should work on windows the same as on linux. If you need to jump on a hangout send me an email (on my profile)

Mark

**Comment by sharryg** [comment]
Hi Mark,

We’ve got it working – it was an issue similar to this one<https://github.com/mdevilliers/rabbitmq-stamp/issues/9> where we had to download the file separately and then scp it to the server.  Thanks for your offer of help – much appreciated.  I’ll try to remember to post an update in a month or so once we’ve bedded the queue cluster in on how the plugin and the signalR scaleout is working.

Thanks,
Sam

**Comment by mdevilliers** [comment]
Awesome,

Mark

**Comment by mdevilliers** [comment]
Hey @sharryg - did you ever test out the scaleout? 

Thanks,

Mark

**Comment by esdevelopment** [comment]
Hi Mark,

We have been successfully using the scaleout with RabbitMQ 3.6.10, Erlang 18.0 in a clustered setup (two nodes) on linux.

Cheers,
Sam

**Comment by sharryg** [comment]
Hi Mark,

We have been successfully using the scaleout with RabbitMQ 3.6.10, Erlang 18.0 in a clustered setup (two nodes) on linux.

Cheers,
Sam

**Comment by mdevilliers** [comment]
Awesome, thanks for the feedback
