### ISSUE TITLE
Version for rabbitmq 3.7.0 and erlang 20.1 

### ISSUE THREAD

**Issue by paulcaru** [mdevilliers/rabbitmq-stamp#14]
Hi,

After upgrading to rabbitmq 3.7.0 and erlang 20.1, we are getting the following error 

"Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=541, text="INTERNAL_ERROR", classId=0, methodId=0, cause="

 We are using rabbitmq_stamp-1.0.4.ez.

Any idea what the issue might be? I'm, thinking we need a new compiled version. Currently installed is . rabbitmq_stamp-1.0.4.ez

**Comment by mdevilliers** [comment]
Hey,

I'm afraid I don't know what the issue could be. I would checkout the logs and see if there are any clues in there - RMQ's logs are pretty awesome.

Compiling a version for yourself should be straightforward
 
- checkout the `new-structure-mk` branch
- change the line in the Makefile 

```
# sets the current version of rabbit rather than working of master
current_rmq_ref = rabbitmq_v3_7_0
```
- run `make`
- run `make tests`
- run `make dist`


Thanks,

Mark

**Comment by mdevilliers** [comment]
Just to say I go some feedback from another user that the new build structure and code changes were good and have merged into master.

**Comment by paulcaru** [comment]
Hi Mark,

Thanks for getting back to me.

Today I tested a bit more and this version broke with rabbit mq version 3.70.0 as it worked when tested with 3.6.16.

I also tried to build the plugin myself on mac but it was hard and finally gave up and looked at an alternative which I managed to achieve. Maybe someone can manage to build it for the future. Thanks a lot for your help once again.
