### ISSUE TITLE
Cannot enable plugin (RabbitMQ 3.6.14 & Erlang 18.3)

### ISSUE THREAD

**Issue by samartzidis** [mdevilliers/rabbitmq-stamp#15]
I have copied your rabbitmq-stamp/compiled/1.0.4/rabbitmq_3_6_3/erlang_18/ compiled plugin under /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.14/plugins on a RabbitMQ 3.6.14 & Erlang 18.3 installation. The plugin does not get listed and when I try to install it I get an error:

rabbitmq-plugins enable rabbitmq_stamp
Error: The following plugins could not be found:
  rabbitmq_stamp

Any hints what I might be doing wrong? Is it just a version incompatibility or a missing dependency?

I would also like to ask what is the specific requirement of the SignalR backplane protocol that makes SignalR.RabbitMq require a custom message exchange. Is it anything that has to do with the message ordering of the backplane message ids maybe?

Thank you.

**Comment by mdevilliers** [comment]
Hey George,

I know you have probably tired this but did you register the plugin as well as copying it into place as per the instructions here - https://www.rabbitmq.com/plugins.html

There might be problems with the different minor versions of Rabbit but usually you are good. If you think there might be the thing to do is compile a version for yourself -

Change the line in the Makefile if you need a specific version -
```
# sets the current version of rabbit rather than working of master
current_rmq_ref = rabbitmq_v3_7_0
```
- run `make`
- run `make tests`
- run `make dist`

You are right the custom plugin is required to guarantee the ordering of messages - SignalR's design requires it.

Mark

**Comment by samartzidis** [comment]
Thanks for the answer and for the great code Mark. Yes I tried the registration bit, which did not work; so as suggested I will revert to full compilation! Cheers!
