### ISSUE TITLE
Trouble with RMQ 3.4.3 / Erlang 17.4

### ISSUE THREAD

**Issue by mthird** [mdevilliers/rabbitmq-stamp#6]
I was unable to load the pre-built binary for 3.4 because it crashed the process, so I compiled a custom version using the latest code-base.  The exchange loaded correctly, but connections from SignalR didn't appear to go through.

I followed your testing approach from the other project (https://github.com/mdevilliers/SignalR.RabbitMq/issues/13) and saw the following stack trace in the log:

```
=ERROR REPORT==== 24-Mar-2015::12:32:50 ===
** Generic server rabbit_stamp_worker terminating
** Last message in was {'$gen_cast',
                        {next,'signalr-stamp',<<"/">>,
                         {delivery,true,true,<0.25534.16>,
                          {basic_message,
                           {resource,<<"/">>,exchange,<<"signalr-stamp">>},
                           [<<>>],
                           {content,60,
                            {'P_basic',undefined,undefined,
                             [{<<"forward_exchange">>,longstr,
                               <<"signalr-test">>}],
                             1,undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined,undefined,
                             undefined,undefined},
                            none,none,
                            [<<>>]},
                           <<139,88,2,25,131,123,26,109,188,102,189,229,133,58,
                             65,44>>,
                           false},
                          1}}}
** When Server state == []
** Reason for termination ==
** {{badrecord,delivery},
    [{rabbit_stamp_worker,handle_cast,2,
                          [{file,"src/rabbit_stamp_worker.erl"},{line,49}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
```

I'm unable to tell what the problem is when looking at the source.  Any ideas.

Relevant bits of info:
OS is CentOS 6 x64 
Erlang/OTP 17.4
RabbitMQ 3.4.3

The stamp exchange is compiled from the most recent code as of today.

**Comment by mthird** [comment]
After some more digging, the line in question is

```
BasicMessage = Message#delivery.message,
```

The Message structure is

```
debug: {delivery,true,true,<0.22884.18>,
           {basic_message,
               {resource,<<"/">>,exchange,<<"signalr-stamp">>},
               [<<>>],
               {content,60,
                   {'P_basic',undefined,undefined,
                       [{<<"forward_exchange">>,longstr,<<"stamp-test">>}],
                       1,undefined,undefined,undefined,undefined,undefined,
                       undefined,undefined,undefined,undefined,undefined},
                   none,none,
                   [<<"testing">>]},
               <<164,28,13,3,119,92,243,153,106,181,245,137,15,11,231,105>>,
               false},
           1}
```

**Comment by mdevilliers** [comment]
Hey - Cool - looks like they have changed the format of the message.
I should have a chance to look at this tonight - just pulling down the latest code.

Mark

**Comment by mdevilliers** [comment]
Actually I'll contradict myself - I don't think they have changed the format

Your message -
```
   {basic_message,
      {resource,<<"/">>,exchange,<<"signalr-stamp">>},
      [<<>>],
      {content,60,
         {'P_basic',undefined,undefined,
             [{<<"forward_exchange">>,longstr,<<"stamp-test">>}],
             1,undefined,undefined,undefined,undefined,undefined,
              undefined,undefined,undefined,undefined,undefined},
          none,none,
          [<<"testing">>]},
       <<164,28,13,3,119,92,243,153,106,181,245,137,15,11,231,105>>,
    false},
```

My message - 
```
 {basic_message,
      {resource,<<"/">>,exchange,<<"demo-exchange">>},
      [<<"my_routing_key">>],
      {content,60,
          {'P_basic',undefined,undefined,
              [{<<"forward_exchange">>,longstr,<<"mydestinationexchange">>}],
              1,undefined,undefined,undefined,undefined,undefined,undefined,
              undefined,undefined,undefined,undefined},
          none,none,
          [<<"foobar">>]},
      <<177,6,255,57,239,0,211,188,85,140,178,46,99,106,77,65>>,
      false}
```

Which look barring some binarys and strings look pretty similar.

Is there any chance you could email me the plugin file you have compiled? My email is markdevilliers at gmail dot com.

Do you still have the message from the log when you tried running the original plugin? The one that took down the process? I have tried it with Rabbit 3.4.4 and Erlang 17.1 with success - however not on centos.

Thanks for your help on this,

Mark

**Comment by mdevilliers** [comment]
Hey - I've had a look at the message formats and they look pretty much the same.

Would it be possible for you to email me the plugin file you are using? My email is markdevilliers at gmail dot com.

Do you also have the error message when Rabbit crashed using the compiled plugin? I have tested it with RabbitMQ 3.4.3 and Erlang 17.1 but not on centos. Although I don't think it should make a difference I am curious?

Thanks for your help,

Mark

**Comment by mthird** [comment]
I'll send you an email with the plugin, but I suspect it is a problem with the HEAD on the rabbitmq-public repository.  I went back and loaded the pre-built binary and, magically, everything works now.

Sorry for the false alarm.

**Comment by mdevilliers** [comment]
Cool its all sorted out. If you come across any other issues or if you have any more queries then don't hesitate either as an issue or as via email.

Mark
