### ISSUE TITLE
RabbitMQ Server 3.5.1

### ISSUE THREAD

**Issue by daleua** [mdevilliers/rabbitmq-stamp#7]
Hi Mark,

Is there any known issue affecting this plugin that makes it not appear in the list of plugins in the rabbitmq plugins folder?

I have installed it in other RabbitMQ servers in Windows with no problem in previous versions (3.4.3) and wondering if the new version is not compatible or it's a problem with my installation of RabbitMQ Server on a Linux box (version 3.5.1).

Thanks,

David Aleu

**Comment by daleua** [comment]
All sorted, using wget to copy the file in the server makes the .ez file not recognisable by rabbitmq server. I copied using scp and it now works.

**Comment by mdevilliers** [comment]
Cool - great news - it would be great to get some feedback on how you get on using 3.5.1 either as an issue or fell free to email me markdevilliers at gmail dot com ?

Thanks, 

Mark
