### ISSUE TITLE
RabbitMQ 3.3.1 with Erlang 17

### ISSUE THREAD

**Issue by guitoux1** [mdevilliers/rabbitmq-stamp#8]
Hi,

Is it possible to have a aother version of the plugin (1.0.3) but for the pair RabbitMQ 3.3(.1) and Erlang 17 plz ?  'Cause I use theses versions and I can't change :(

Thanks

**Comment by mdevilliers** [comment]
No problem i'll see what I can do.

**Comment by guitoux1** [comment]
Thank you !

**Comment by mdevilliers** [comment]
Do you want to test the plug in at 
https://github.com/mdevilliers/rabbitmq-stamp/tree/master/compiled/1.0.3/rabbitmq_3_3_1/erlang_17

The unit and integration tests all pass but if you could feedback that would be great?

Mark

**Comment by guitoux1** [comment]
Thanks Mark ! Iwill test it ASAP and give you a feedback.

**Comment by guitoux1** [comment]
It works just fine, thanks !
