### ISSUE TITLE
rabbitmq-stamp with RHEL/CentOS

### ISSUE THREAD

**Issue by 2LargeFeet** [mdevilliers/rabbitmq-stamp#9]
I'm unable to install stamp on CentOS 7. I've tried with both rabbitmq-server 3.5.6 and rabbitmq-server 3.4.2 and erlang 17. I get the following error.

Problem reading some plugins: [{"/usr/lib/rabbitmq/lib/rabbitmq_server-3.4.2/sbin/../plugins/rabbitmq_stamp-1.0.3.ez",
                                {invalid_ez,einval}}]

Is Stamp compatible with RHEL distros? I haven't had an issue installing on Ubuntu.

[2LargeFeet@localhost log]$ sudo yum list erlang rabbitmq-server
Installed Packages
erlang.x86_64                                                                           R16B-03.11.el7
rabbitmq-server.noarch                                                                  3.4.2-1

[2LargeFeet@localhost log]$ cat /proc/version
Linux version 3.10.0-229.20.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Nov 3 19:10:07 UTC 2015

I installed from:

wget https://github.com/mdevilliers/rabbitmq-stamp/blob/master/compiled/1.0.3/rabbitmq_3_4/erlang_17/rabbitmq_stamp-1.0.3.ez

**Comment by mdevilliers** [comment]
Hey,

I think I've worked it out. 

```
wget https://github.com/mdevilliers/rabbitmq-stamp/blob/master/compiled/1.0.3/rabbitmq_3_4/erlang_17/rabbitmq_stamp-1.0.3.ez

cat rabbitmq_stamp-1.0.3.ez
````

outputs a whole lot of html for me.

```
wget https://github.com/mdevilliers/rabbitmq-stamp/blob/master/compiled/1.0.3/rabbitmq_3_4/erlang_17/rabbitmq_stamp-1.0.3.ez?raw=true

cat rabbitmq_stamp-1.0.3.ez
````

Downloads the .ez file

Could you look at content of the plugin files content and confirm?

**Comment by 2LargeFeet** [comment]
This worked perfectly! My linux/git skills are so weak! Thank you very much for the help.

**Comment by mdevilliers** [comment]
No problem,

Mark
